# Generated by Django 4.2.1 on 2023-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=200)),
                ('longitude', models.FloatField(max_length=200)),
                ('chargeprice', models.FloatField(max_length=100)),
                ('charger', models.CharField(max_length=50)),
            ],
        ),
    ]
