# Generated by Django 4.2.1 on 2023-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
